#ifndef H_GPGSETUP_DEFAULTS
#define H_GPGSETUP_DEFAULTS

#ifndef CONFIG_RECIPIENT_DEFAULT
#define CONFIG_RECIPIENT_DEFAULT NULL
#endif

#ifndef CONFIG_HOMEDIR_DEFAULT
#define CONFIG_HOMEDIR_DEFAULT NULL
#endif

#ifndef CONFIG_MATERIALDIR_DEFAULT
#define CONFIG_MATERIALDIR_DEFAULT "/var/gpgsetup"
#endif

#ifndef CONFIG_TEMPLATE_DEFAULT
#define CONFIG_TEMPLATE_DEFAULT NULL
#endif

#ifndef CONFIG_TMP_DEFAULT
#define CONFIG_TMP_DEFAULT "/run"
#endif

#ifndef CONFIG_FLAGS_DEFAULT
#define CONFIG_FLAGS_DEFAULT (CONFIG_ARMOUR | CONFIG_GSTDERR)
#endif

#ifndef CONFIG_KEYSIZE_DEFAULT
#define CONFIG_KEYSIZE_DEFAULT 64
#endif

#ifndef BLOB_CIPHER_DEFAULT
#define BLOB_CIPHER_DEFAULT "aes-xts-plain64"
#endif

#ifndef BLOB_HASH_DEFAULT
#define BLOB_HASH_DEFAULT "plain"
#endif

#ifndef BLOB_POSTADD_DEFAULT
#define BLOB_POSTADD_DEFAULT NULL
#endif

#ifndef BLOB_PRERM_DEFAULT
#define BLOB_PRERM_DEFAULT NULL
#endif

#ifndef BLOB_EXPORTS
#define BLOB_EXPORTS BLOB_CIPHER
#endif

#endif // H_GPGSETUP_DEFAULTS
